// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoiseCapture.Web.Data;

#nullable disable

namespace NoiseCapture.Web.Migrations
{
    [DbContext(typeof(NoiseCaptureDbContext))]
    [Migration("20260529090000_RemoveUniqueIndexRecordedAt")]
    partial class RemoveUniqueIndexRecordedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NoiseCapture.Web.Data.NoiseLogEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ContinuedFromLast")
                        .HasColumnType("bit");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Loudness")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("RecordedAtSydney")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Weather")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("NoiseLogEntries", (string)null);
                });

            modelBuilder.Entity("NoiseCapture.Web.Data.NoiseLogEntryLocationEntity", b =>
                {
                    b.Property<int>("NoiseLogEntryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("NoiseLogEntryId", "SortOrder");

                    b.ToTable("NoiseLogEntryLocations", (string)null);
                });

            modelBuilder.Entity("NoiseCapture.Web.Data.NoiseLogEntryNoiseSourceEntity", b =>
                {
                    b.Property<int>("NoiseLogEntryId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("NoiseLogEntryId", "SortOrder");

                    b.ToTable("NoiseLogEntryNoiseSources", (string)null);
                });

            modelBuilder.Entity("NoiseCapture.Web.Data.NoiseLogEntryLocationEntity", b =>
                {
                    b.HasOne("NoiseCapture.Web.Data.NoiseLogEntryEntity", "NoiseLogEntry")
                        .WithMany("Locations")
                        .HasForeignKey("NoiseLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoiseLogEntry");
                });

            modelBuilder.Entity("NoiseCapture.Web.Data.NoiseLogEntryNoiseSourceEntity", b =>
                {
                    b.HasOne("NoiseCapture.Web.Data.NoiseLogEntryEntity", "NoiseLogEntry")
                        .WithMany("NoiseSources")
                        .HasForeignKey("NoiseLogEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoiseLogEntry");
                });

            modelBuilder.Entity("NoiseCapture.Web.Data.NoiseLogEntryEntity", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("NoiseSources");
                });
#pragma warning restore 612, 618
        }
    }
}
