name: 10 Deploy Infrastructure

on:
  push:
    branches: [main]
    paths:
      - "bicep/**"
  schedule:
    - cron: "0 20 * * *"  # 6:00 AM Sydney (AEST, UTC+10)
    - cron: "0 4 * * *"   # 2:00 PM Sydney (AEST, UTC+10)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    #   - name: Create Resource Group
    #     run: az group create --name 'rg-noise-capture' --location 'eastus2'

      - name: Deploy Bicep
        working-directory: bicep
        run: |
          az deployment group create \
            --name 'noise-capture-dev' \
            --resource-group 'rg-noise-capture' \
            --template-file './main.bicep' \
            --parameters './main.bicepparam' \
            --parameters sqlAdministratorPassword='${{ secrets.AZURE_SQL_ADMIN_PASSWORD }}'
